### ISSUE TITLE
MissingKeyParam error in /directory/v1/users/auth/:token

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-directory#15]
Called from ganomede-users (when resetting the password of a user logged-in with Facebook).

```
LOGS FROM GANOMEDE-DIRECTORY

============================================================================================================

[2017-03-03T09:59:41.644Z]  INFO: ganomede-directory/17 on f3b3b057647c: GET /directory/v1/users/auth/<authToken> (req_id=1a8aa481-480e-4218-b8f2-a1df[17/1907]

============================================================================================================

[2017-03-03T09:59:41.656Z] ERROR: ganomede-directory/17 on f3b3b057647c:
    function raised error: (new Error("MissingKeyParam", "lists.profiles", 5))
    stacktrace: ([object Object],[object Object])@lists.profiles:5
    runList(function (head, req) {if (typeof req.query.key !== "string" || req.query.key.length === 0) {throw new Error("MissingKeyParam");}const profile = {id: null, hash: null, aliases: []};var ro
w;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringi
fy(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:989
    (function (head, req) {if (typeof req.query.key !== "string" || req.query.key.length === 0) {throw new Error("MissingKeyParam");}const profile = {id: null, hash: null, aliases: []};var row;var d
oc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(prof
ile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036
    ("_design/d000",[object Array],[object Array])@/usr/local/share/couchdb/server/main.js:1517
    ()@/usr/local/share/couchdb/server/main.js:1562
    @/usr/local/share/couchdb/server/main.js:1573

    --
    Error: function raised error: (new Error("MissingKeyParam", "lists.profiles", 5))
    runList(function (head, req) {if (typeof req.query.key !== "string" || req.query.key.length === 0) {throw new Error("MissingKeyParam");}const profile = {id: null, hash: null, aliases: []};var ro
w;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringi
fy(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:989
    (function (head, req) {if (typeof req.query.key !== "string" || req.query.key.length === 0) {throw new Error("MissingKeyParam");}const profile = {id: null, hash: null, aliases: []};var row;var d
oc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(prof
ile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036
    ("_design/d000",[object Array],[object Array])@/usr/local/share/couchdb/server/main.js:1517
    ()@/usr/local/share/couchdb/server/main.js:1562
    @/usr/local/share/couchdb/server/main.js:1573

        at Object.createErr [as create] (/home/app/code/node_modules/errs/lib/errs.js:97:11)
        at Request._callback (/home/app/code/node_modules/nano/lib/nano.js:248:15)
        at Request.self.callback (/home/app/code/node_modules/request/request.js:186:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (/home/app/code/node_modules/request/request.js:1081:10)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)
        at IncomingMessage.<anonymous> (/home/app/code/node_modules/request/request.js:1001:12)
        at IncomingMessage.g (events.js:291:16)

============================================================================================================

[2017-03-03T09:59:41.657Z]  INFO: ganomede-directory/17 on f3b3b057647c: handled: 500 (req_id=1a8aa481-480e-4218-b8f2-a1df65eba4c7, audit=true, remoteAddress=10.0.2.102, remotePort=57418, latency=13
, _audit=true, req.query={}, req.version=*)
    GET /directory/v1/users/auth/<authToken> HTTP/1.1
    host: account.ggs.ovh
    accept-encoding: gzip
    x-forwarded-for: 88.99.60.238, 162.158.89.184, 10.0.2.1
    cf-ray: 339bbe951d8a234e-FRA
    x-forwarded-proto: https
    cf-visitor: {"scheme":"https"}
    x-request-id: 1a8aa481-480e-4218-b8f2-a1df65eba4c7
    accept: application/json
    user-agent: restify/4.3.0 (x64-linux; v8/5.1.281.93; OpenSSL/1.0.2k) node/6.10.0
    date: Fri, 03 Mar 2017 09:59:16 GMT
    x-newrelic-id: VQYFWVJaCRAIUVdRBQIO
    x-newrelic-transaction: PxQBUl8CDQsBAlRSU1RRXkYdUFIOFQZOElQLW1kNDANVUAkFVAcLQEgUAlMCVQBXBlxDPw==
    cf-connecting-ip: 88.99.60.238
    connection: close
    x-forwarded-port: 80
    --
    HTTP/1.1 500 Internal Server Error
    x-request-id: 1a8aa481-480e-4218-b8f2-a1df65eba4c7
    content-type: application/json
    content-length: 1320
    --
    req.timers: {
      "handler-0": 137,
      "parseQueryString": 8,
      "readBody": 29,
      "parseBody": 4,
      "setRequestId": 12,
      "handler-1": 19,
      "lookupWithToken": 12321
    }

============================================================================================================
============================================================================================================
============================================================================================================
============================================================================================================

LOGS FROM GANOMEDE-USERS

============================================================================================================
============================================================================================================

[2017-03-03T09:59:16.520Z]  INFO: users/17 on 4b0af00cf8d8: POST /users/v1/auth/<authToken>/passwordResetEmail (req_id=1a8aa481-480e-4218-b8f2-a1df65eba4c7)

============================================================================================================

[2017-03-03T09:59:16.521Z]  INFO: users/17 on 4b0af00cf8d8: (req_id=1a8aa481-480e-4218-b8f2-a1df65eba4c7)
    reset password { token: '<authToken>',
      email: undefined }

============================================================================================================

[2017-03-03T09:59:16.570Z] DEBUG: users/17 on 4b0af00cf8d8: directoryClient.get (req_id=1a8aa481-480e-4218-b8f2-a1df65eba4c7, resBody=[Circular])
    options: {
      "path": "/directory/v1/users/auth/<authToken>",
      "headers": {
        "x-request-id": "1a8aa481-480e-4218-b8f2-a1df65eba4c7",
        "accept": "application/json",
        "user-agent": "restify/4.3.0 (x64-linux; v8/5.1.281.93; OpenSSL/1.0.2k) node/6.10.0",
        "date": "Fri, 03 Mar 2017 09:59:16 GMT"
      }
    }
    --
    resErr: {
      "jse_shortmsg": "",
      "jse_info": {},
      "message": "{\"message\":\"function raised error: (new Error(\\\"MissingKeyParam\\\", \\\"lists.profiles\\\", 5)) \\nstacktrace: ([object Object],[object Object])@lists.profiles:5\\nrunList(fu
nction (head, req) {if (typeof req.query.key !== \\\"string\\\" || req.query.key.length === 0) {throw new Error(\\\"MissingKeyParam\\\");}const profile = {id: null, hash: null, aliases: []};var row;
var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify
(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:989\\n(function (head, req) {if (typeof req.query.key !== \\\"string\\\" || req.query.key.length === 0) {throw ne
w Error(\\\"MissingKeyParam\\\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profi
le.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\\n(\\\"_design
/d000\\\",[object Array],[object Array])@/usr/local/share/couchdb/server/main.js:1517\\n()@/usr/local/share/couchdb/server/main.js:1562\\n@/usr/local/share/couchdb/server/main.js:1573\\n\"}",
      "statusCode": 500,
      "body": {
        "message": "function raised error: (new Error(\"MissingKeyParam\", \"lists.profiles\", 5)) \nstacktrace: ([object Object],[object Object])@lists.profiles:5\nrunList(function (head, req) {if
(typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())
) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[o
bject Array])@/usr/local/share/couchdb/server/main.js:989\n(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const
profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = pr
ofile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\n(\"_design/d000\",[object Array],[object Array])@/usr
/local/share/couchdb/server/main.js:1517\n()@/usr/local/share/couchdb/server/main.js:1562\n@/usr/local/share/couchdb/server/main.js:1573\n"
      }
    }

============================================================================================================

[2017-03-03T09:59:16.570Z] DEBUG: users/17 on 4b0af00cf8d8: sendPasswordResetEmail with primary failed (req_id=1a8aa481-480e-4218-b8f2-a1df65eba4c7)
    err: {
      "jse_shortmsg": "",
      "jse_info": {},
      "message": "{\"message\":\"function raised error: (new Error(\\\"MissingKeyParam\\\", \\\"lists.profiles\\\", 5)) \\nstacktrace: ([object Object],[object Object])@lists.profiles:5\\nrunList(fu
nction (head, req) {if (typeof req.query.key !== \\\"string\\\" || req.query.key.length === 0) {throw new Error(\\\"MissingKeyParam\\\");}const profile = {id: null, hash: null, aliases: []};var row;
var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify
(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:989\\n(function (head, req) {if (typeof req.query.key !== \\\"string\\\" || req.query.key.length === 0) {throw ne
w Error(\\\"MissingKeyParam\\\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profi
le.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\\n(\\\"_design
/d000\\\",[object Array],[object Array])@/usr/local/share/couchdb/server/main.js:1517\\n()@/usr/local/share/couchdb/server/main.js:1562\\n@/usr/local/share/couchdb/server/main.js:1573\\n\"}",
      "statusCode": 500,
      "body": {
        "message": "function raised error: (new Error(\"MissingKeyParam\", \"lists.profiles\", 5)) \nstacktrace: ([object Object],[object Object])@lists.profiles:5\nrunList(function (head, req) {if
(typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())
) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[o
bject Array])@/usr/local/share/couchdb/server/main.js:989\n(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const
profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = pr
ofile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\n(\"_design/d000\",[object Array],[object Array])@/usr
/local/share/couchdb/server/main.js:1517\n()@/usr/local/share/couchdb/server/main.js:1562\n@/usr/local/share/couchdb/server/main.js:1573\n"
      }
    }

============================================================================================================

[2017-03-03T09:59:16.571Z] ERROR: users/17 on 4b0af00cf8d8: {"message":"function raised error: (new Error(\"MissingKeyParam\", \"lists.profiles\", 5)) \nstacktrace: ([object Object],[objec[291/1962]
@lists.profiles:5\nrunList(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null,
aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases)
;}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:989\n(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length
=== 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.
hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\n(
\"_design/d000\",[object Array],[object Array])@/usr/local/share/couchdb/server/main.js:1517\n()@/usr/local/share/couchdb/server/main.js:1562\n@/usr/local/share/couchdb/server/main.js:1573\n"}
    InternalServerError: {"message":"function raised error: (new Error(\"MissingKeyParam\", \"lists.profiles\", 5)) \nstacktrace: ([object Object],[object Object])@lists.profiles:5\nrunList(function
 (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while
((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[
object Object],[object Array])@/usr/local/share/couchdb/server/main.js:989\n(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKe
yParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;pro
file.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\n(\"_design/d000\",[object Array],[ob
ject Array])@/usr/local/share/couchdb/server/main.js:1517\n()@/usr/local/share/couchdb/server/main.js:1562\n@/usr/local/share/couchdb/server/main.js:1573\n"}
        at ClientRequest.onResponse (/home/app/code/node_modules/restify/lib/clients/http_client.js:169:26)
        at ClientRequest.g (events.js:291:16)
        at emitOne (events.js:96:13)
        at ClientRequest.emit (events.js:188:7)
        at ClientRequest.wrapped (/home/app/code/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
        at ClientRequest.wrappedRequestEmit [as emit] (/home/app/code/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:52:26)
        at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
        at TLSSocket.socketOnData (_http_client.js:363:20)
        at emitOne (events.js:96:13)
        at TLSSocket.emit (events.js:188:7)
        at TLSSocket.wrapped (/home/app/code/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
        at TLSSocket.wrappedEmit [as emit] (/home/app/code/node_modules/newrelic/lib/transaction/tracer/index.js:220:46)
        at readableAddChunk (_stream_readable.js:176:18)
        at TLSSocket.Readable.push (_stream_readable.js:134:10)
        at TLSWrap.onread (net.js:548:20)
        at TLSWrap.wrapped [as onread] (/home/app/code/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)

============================================================================================================

[2017-03-03T09:59:16.571Z] ERROR: users/17 on 4b0af00cf8d8: {"message":"function raised error: (new Error(\"MissingKeyParam\", \"lists.profiles\", 5)) \nstacktrace: ([object Object],[object Object])
@lists.profiles:5\nrunList(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null,
aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases)
;}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:989\n(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length
=== 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.
hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\n(
\"_design/d000\",[object Array],[object Array])@/usr/local/share/couchdb/server/main.js:1517\n()@/usr/local/share/couchdb/server/main.js:1562\n@/usr/local/share/couchdb/server/main.js:1573\n"} (req_
id=1a8aa481-480e-4218-b8f2-a1df65eba4c7)
    InternalServerError: {"message":"function raised error: (new Error(\"MissingKeyParam\", \"lists.profiles\", 5)) \nstacktrace: ([object Object],[object Object])@lists.profiles:5\nrunList(function
 (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while
((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[
object Object],[object Array])@/usr/local/share/couchdb/server/main.js:989\n(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKe
yParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;pro
file.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\n(\"_design/d000\",[object Array],[ob
ject Array])@/usr/local/share/couchdb/server/main.js:1517\n()@/usr/local/share/couchdb/server/main.js:1562\n@/usr/local/share/couchdb/server/main.js:1573\n"}
        at ClientRequest.onResponse (/home/app/code/node_modules/restify/lib/clients/http_client.js:169:26)
        at ClientRequest.g (events.js:291:16)
        at emitOne (events.js:96:13)
        at ClientRequest.emit (events.js:188:7)
        at ClientRequest.wrapped (/home/app/code/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
        at ClientRequest.wrappedRequestEmit [as emit] (/home/app/code/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:52:26)
        at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
        at TLSSocket.socketOnData (_http_client.js:363:20)
        at emitOne (events.js:96:13)
        at TLSSocket.emit (events.js:188:7)
        at TLSSocket.wrapped (/home/app/code/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
        at TLSSocket.wrappedEmit [as emit] (/home/app/code/node_modules/newrelic/lib/transaction/tracer/index.js:220:46)
        at readableAddChunk (_stream_readable.js:176:18)
        at TLSSocket.Readable.push (_stream_readable.js:134:10)
        at TLSWrap.onread (net.js:548:20)
        at TLSWrap.wrapped [as onread] (/home/app/code/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)

============================================================================================================

[2017-03-03T09:59:16.572Z]  INFO: users/17 on 4b0af00cf8d8: handled: 500 (req_id=1a8aa481-480e-4218-b8f2-a1df65eba4c7, audit=true, remoteAddress=::ffff:10.0.2.103, remotePort=39960, latenc[226/1962]
it=true, req.query="", req.version=*)
    POST /users/v1/auth/<authToken>/passwordResetEmail HTTP/1.1
    host: prod.ggs.ovh
    accept-encoding: gzip
    x-forwarded-for: 146.185.39.111, 162.158.22.187, 10.0.2.1
    cf-ray: 339bbe947e775ff9-MRS
    content-length: 0
    x-forwarded-proto: https
    cf-visitor: {"scheme":"https"}
    cookie: __cfduid=d3c31c32708439a5cbe12a3e5f788a13e1473830810
    user-agent: Mozilla/5.0 (Android; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/23.0
    x-flash-version: 23,0,0,162
    referer: app:/Triominos.swf
    accept: application/json
    content-type: application/json
    cf-connecting-ip: 146.185.39.111
    connection: close
    x-forwarded-port: 80
    --
    HTTP/1.1 500 Internal Server Error
    x-request-id: 1a8aa481-480e-4218-b8f2-a1df65eba4c7
    content-type: application/json
    content-length: 1320

    {
      "message": "function raised error: (new Error(\"MissingKeyParam\", \"lists.profiles\", 5)) \nstacktrace: ([object Object],[object Object])@lists.profiles:5\nrunList(function (head, req) {if (t
ypeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const profile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow()))
{doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = profile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[obj
ect Array])@/usr/local/share/couchdb/server/main.js:989\n(function (head, req) {if (typeof req.query.key !== \"string\" || req.query.key.length === 0) {throw new Error(\"MissingKeyParam\");}const pr
ofile = {id: null, hash: null, aliases: []};var row;var doc;while ((row = getRow())) {doc = row.value;profile.id = profile.id || doc.id;profile.hash = profile.hash || doc.hash;profile.aliases = prof
ile.aliases.concat(doc.aliases);}send(JSON.stringify(profile));},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:1036\n(\"_design/d000\",[object Array],[object Array])@/usr/l
ocal/share/couchdb/server/main.js:1517\n()@/usr/local/share/couchdb/server/main.js:1562\n@/usr/local/share/couchdb/server/main.js:1573\n"
    }
    --
    req.timers: {
      "handler-0": 169,
      "readBody": 40,
      "parseBody": 30,
      "setRequestId": 50,
      "passwordResetEmail": 50945
    }
```

**Comment by j3k0** [comment]
@elmigranto I have a hard time figure out what causes the problem here. Anyway it would be nice to catch those before throwing an exception in couchdb's view... so there's a little more insight on what is going wrong.

Any idea?

**Comment by j3k0** [comment]
most probably the caller is `db.list` from `src/db/db.js`... `qs` might not be correct here.

**Comment by j3k0** [comment]
Hope I'm on the right path... ba04a47

**Comment by j3k0** [comment]
`db.viewWithList` is called with the following
```
[2017-03-03T13:04:04.896Z] DEBUG: ganomede-directory/12 on 57f4f9df6742: db.viewWithList (designName=d000, viewname=rawProfiles, listname=profiles)
    qs: {
      "key": {
        "username": "Jeko488",
        "email": "jchoelt@gmail.com"
      }
    }
```

`key` isn't a string, as expected by the view.

**Comment by elmigranto** [comment]
Sorry I wasn't available earlier to help you with this.

I think the problem is that "new" authdb is `token -> username` and the old one is `token -> account JSON`. This got me thinking that yeah, errors that we do not wrap have non-useful stack traces… Also, probably worth pulling out authdb middleware and not use it directly.

**Comment by elmigranto** [comment]
Couple of quick ideas:
  - wrap _all errors_ (with WError we can have reason error object)
  - print `new Error().stack` (or similar) in `sendHttpError` so we know where it came from.
