### ISSUE TITLE
Trim leading/trailing white space in alias values

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-directory#23]
Some aliases (emails in our case) sometimes have leading/trailing spaces...

We need to:

 - [x] clean the database of bad data
   - for all documents with `_id` containing one or more spaces, add a newer alias with spaces removed, and date + 1ms, so it becomes the most recent one.
 - [x] fix any incoming alias values by trim out spaces from them in POST and GET requests.
 - [ ] update README: doc that spaces are trimmed from alias values.

**Comment by j3k0** [comment]
@elmigranto I took care of cleaning the database, 6c53808

**Comment by j3k0** [comment]
Woops

```
[2017-04-22T06:17:51.901Z]  INFO: ganomede-directory/27 on b22785884872: GET /directory/v1/users/alias/email/xxx (req_id=da0fc6c5-2bac-403a-826d-b6
7c4d4baf2f)
[2017-04-22T06:17:51.907Z] FATAL: ganomede-directory/27 on b22785884872: Assignment to constant variable.
    TypeError: Assignment to constant variable.
        at Server.lookupWithAlias (/home/app/code/src/directory.router.js:135:11)
        at next (/home/app/code/node_modules/restify/lib/server.js:912:30)
        at f (/home/app/code/node_modules/once/once.js:25:25)
        at Server.server.use (/home/app/code/src/server.js:66:5)
        at next (/home/app/code/node_modules/restify/lib/server.js:912:30)
        at f (/home/app/code/node_modules/once/once.js:25:25)
        at Server.setRequestId (/home/app/code/src/server.js:56:12)
        at next (/home/app/code/node_modules/restify/lib/server.js:912:30)
        at f (/home/app/code/node_modules/once/once.js:25:25)
        at Server.parseBody (/home/app/code/node_modules/restify/lib/plugins/body_parser.js:52:17)
```
